# -*- coding: utf-8 -*-
"""Digit Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AI-MlmIuvQGjvi-kGkaxAYHCCiZLLl-l
"""

from PIL import Image
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import joblib
import numpy as np
import mnist

#Training
x_train = mnist.train_images()
y_train = mnist.train_labels()

x_test = mnist.test_images()
y_test = mnist.test_labels()

x_train = x_train.reshape((-1,28*28))
x_test = x_test.reshape((-1,28*28))

x_train = (x_train)/256
x_test = (x_test)/256

clf = MLPClassifier(solver="adam",activation="relu",hidden_layer_sizes=(70,70))

clf.fit(x_train,y_train)

prediction = clf.predict(x_test)

acc = confusion_matrix(y_test,prediction)

print(acc)

def accuracy(cm):
  diagonal = cm.trace()
  ele = cm.sum()
  return diagonal/ele

result = accuracy(acc)

print(result) #accuracy

joblib.dump(clf,"model.sav")

